name: Shell Comands
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        shell: python
        run: |
          import os
          print(os.getenv('GITHUB_WORKFLOW'), 'no value set')
      - name: checkout
        uses: actions/checkout@v2
      - name: list files
        run: ls -aR